In [4]:
import torch.nn as nn 
import torch.optim as optim 
import numpy as np 
import torch 
from tqdm import tqdm 
import torchvision
from torchvision.transforms import transforms
from torch.utils.data import Dataset, DataLoader, random_split
import pathlib
import matplotlib.pyplot as plt
from glob import glob 
import pandas as pd 
import os
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, confusion_matrix, ConfusionMatrixDisplay

import argparse
from PIL import Image
from torchvision.models import EfficientNet_B0_Weights

In [2]:
images = sorted(glob('/mnt/Enterprise2/shirshak/Glaucoma_Dataset_Drishti-GS/Drishti-GS1_preprocessed_cropped_separated_train_test_val/test/*/*.png'))
df = pd.DataFrame(columns=["Image Name", "height", "width", "label", "train_val_test", "Mean Intensity Value", "Mean Intensity Value R,G,B"])

for index, image in enumerate(tqdm(images)):
    img_name = image.split("/")[-1]
    height = torchvision.io.read_image(image).shape[1]
    width = torchvision.io.read_image(image).shape[2]
    train_val_test = image.split("/")[-3]
    label = image.split("/")[-2]
    mean_intensity = torchvision.io.read_image(image).float().mean()
    mean_intensity_per_channel = torchvision.io.read_image(image).float().mean(dim=[1, 2])
    df.loc[index] = {
        "Image Name": img_name,
        "height": height,
        "width": width, 
        "label": label, 
        "train_val_test": train_val_test,
        "Mean Intensity Value": mean_intensity.item(),
        "Mean Intensity Value R,G,B": mean_intensity_per_channel.tolist()
        }
print(df)
# df.to_csv("/home/shirshak/BPEye_Project_2024/zzz_tests/df_DRISTI_H_W_Mean-Intensity_labels.csv", index=False)


100%|██████████| 101/101 [00:40<00:00,  2.47it/s]

            Image Name  height  width label train_val_test  \
0    drishtiGS_007.png    2048   2048   NRG           test   
1    drishtiGS_008.png    2048   2048   NRG           test   
2    drishtiGS_009.png    2047   2047   NRG           test   
3    drishtiGS_013.png    2407   2407   NRG           test   
4    drishtiGS_017.png    2048   2048   NRG           test   
..                 ...     ...    ...   ...            ...   
96   drishtiGS_083.png    2048   2048    RG           test   
97   drishtiGS_084.png    2047   2047    RG           test   
98   drishtiGS_086.png    2048   2048    RG           test   
99   drishtiGS_087.png    2047   2047    RG           test   
100  drishtiGS_088.png    2046   2046    RG           test   

     Mean Intensity Value                         Mean Intensity Value R,G,B  
0               58.485668  [103.0355453491211, 56.30249786376953, 16.1189...  
1               54.452911  [92.03231811523438, 50.24470520019531, 21.0816...  
2               33

In [2]:
df = pd.read_csv("/home/shirshak/BPEye_Project_2024/zzz_tests/df_DRISTI_H_W_Mean-Intensity_labels.csv")

In [1]:
df.height.min(), df.height.max()

NameError: name 'df' is not defined

In [5]:
df.height.unique()

array([2048, 2047, 2407, 2049, 2046, 2051, 2044, 2133, 2050, 2045, 2427,
       2395, 2226, 2443, 2137, 2467])

In [ ]:
2047, 2048, 2049, 2046,2051, 2044, 2050, 2045

In [5]:
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, roc_curve
X, y = load_breast_cancer(return_X_y=True)
clf = LogisticRegression(solver="liblinear", random_state=0).fit(X, y)
roc_curve(y, clf.predict_proba(X)[:, 1])
# roc_auc_score(y, clf.decision_function(X))

(array([0.        , 0.        , 0.        , 0.00471698, 0.00471698,
        0.00943396, 0.00943396, 0.01415094, 0.01415094, 0.01886792,
        0.01886792, 0.02358491, 0.02358491, 0.02830189, 0.02830189,
        0.03773585, 0.03773585, 0.04245283, 0.04245283, 0.06132075,
        0.06132075, 0.06603774, 0.06603774, 0.08490566, 0.08490566,
        0.08962264, 0.08962264, 0.09433962, 0.09433962, 0.0990566 ,
        0.0990566 , 0.11792453, 0.11792453, 0.14150943, 0.14150943,
        1.        ]),
 array([0.        , 0.00280112, 0.71708683, 0.71708683, 0.87955182,
        0.87955182, 0.93557423, 0.93557423, 0.93837535, 0.93837535,
        0.94677871, 0.94677871, 0.94957983, 0.94957983, 0.95518207,
        0.95518207, 0.95798319, 0.95798319, 0.96638655, 0.96638655,
        0.9719888 , 0.9719888 , 0.97478992, 0.97478992, 0.97759104,
        0.97759104, 0.9859944 , 0.9859944 , 0.99159664, 0.99159664,
        0.99439776, 0.99439776, 0.99719888, 0.99719888, 1.        ,
        1.        ]),
 arr